- name: restart nelson
  systemd:
    name: nelson.service
    enabled: true
    daemon_reload: yes
    state: restarted

- name: restart nelson-gui
  systemd:
    name: nelson-gui.service
    enabled: true
    daemon_reload: yes
    state: restarted
