- name: restart iota-pm
  systemd:
    name: iota-pm.service
    state: restarted
    enabled: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
    enabled: yes

- name: reload systemd
  command: systemctl daemon-reload
