- name: restart field
  systemd:
    name: field.service
    daemon_reload: yes
    enabled: true
    state: restarted

- name: restart field-exporter
  systemd:
    name: field-exporter.service
    daemon_reload: yes
    state: restarted
    enabled: yes
