# Unprivileged user to run iri with
iri_username: iri

# Base directory where iri is installed and runs from
iri_basedir: /var/lib/iri

# The iri version to install. E.g. to get the latest: https://github.com/iotaledger/iri/releases/latest
iri_version: 1.4.1.2

# The TCP port on which IRI listens for API calls and allows for light wallets to connect to
iri_api_port: 14265

# The UDP neighbor peering port
iri_udp_port: 14600

# The TCP neighbor peering port
iri_tcp_port: 14600

# Limit IRI memory usage
iri_java_mem: 4096m

# Initial memory usage
iri_init_java_mem: 1024m

# Exclude from the API the commands below
# works in conjunction with `--remote` / `api_port_remote: true`
iri_remote_limit_api: "removeNeighbors, addNeighbors, interruptAttachingToTangle, attachToTangle, getNeighbors"

# Let the iri_api_port bind to all interfaces (0.0.0.0).
# `true` is necessary in order to allow external wallets/APIs to connect without tunneling.
# If set to `false` it will only bind to localhost (127.0.0.1)
api_port_remote: false
