# Change to 0.0.0.0 to bind to all interfaces (expose remotely)
lb_bind_address: 127.0.0.1

# This will be the external accessible port
iri_api_port_remote: 14267

# Max connections to API
iri_api_max_connections: 12

# Enable remote auth with password (uses the same as iotapm/grafana)
iri_remote_auth: false

# Load balancer max connections (all backends)
lb_max_connections: 24

# Stats port for haproxy
haproxy_stats_port: 9292

# Stats bind to address
haproxy_stats_address: 127.0.0.1

haproxy_dir: '/opt/haproxy'
haproxy_username: haproxy
haproxy_base_version: 1.8
haproxy_min_version: 3

# A list of IPs to whitelist on haproxy
# This will allow those IPs to bypass command 
# regex limitations. The format is a yaml list
# thus ['value', 'value'] or `- value` on each
# new line.
haproxy_whitelist:
  - 127.0.0.1

# Commands to deny access to
haproxy_deny_regex: '(get|remove|add)Neighbors|attachToTangle|interruptAttachingToTangle'

# Bad commands regex example
haproxy_bad_command: '\"getTransactionsToApprove\"(.*)GFCCGTGSUEVBZYFK9QNAHOVHXUMEATUFLGBZLDKMOGWCXVUZDVEJVCLLCJJ9NQOIMOLMUMFMGZSI99999'
