- name: ensure firewalld started and enabled
  systemd:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: allow nginx ports in firewall
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - "{{ prom_nginx_port }}"
    - "{{ grafana_nginx_port }}"
    - "{{ alertmanager_nginx_port }}"
  when: >
        install_nginx is defined and install_nginx and
        (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: allow prometheus grafana nginx port via selinux seport
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  with_items:
    - "{{ prom_nginx_port }}"
    - "{{ grafana_nginx_port }}"
    - "{{ alertmanager_nginx_port }}"
  when: >
        install_nginx is defined and install_nginx and
        (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: allow nginx to revese proxy
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: >
        install_nginx is defined and install_nginx and
        (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: allow prometheus and grafana nginx port in firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ item }}"
  with_items:
    - "{{ prom_nginx_port }}"
    - "{{ grafana_nginx_port }}"
    - "{{ alertmanager_nginx_port }}"
  when: >
        install_nginx is defined and install_nginx and
        (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
