- name: restart iri
  systemd:
    name: iri.service
    state: restarted
    enabled: yes

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload
