- name: restart iri
  systemd:
    name: iri.service
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes

- name: reload systemd
  command: systemctl daemon-reload

- name: restart systemd-journald
  systemd:
    name: systemd-journald
    state: restarted
