# --- Ubuntu

# Required, else jq and some other packages fail
- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install software-properties-common
  apt: state=latest name=software-properties-common update_cache=yes

### Installation via packages disabled due to the chance
### of Oracle changing links/versions. Update will be
### faster in the playbook rather than wait for ppa:webupd8team/java
#- name: apt add repository
#  apt_repository:
#    repo: 'ppa:webupd8team/java'
#    state: present

#- name: debian | ensure the webupd8 launchpad apt repository key is present
#  apt_key:
#    id=0xC2518248EEA14886
#    keyserver=keyserver.ubuntu.com
#    state=present

#- name: set license as accepted
#  debconf:
#    name: 'oracle-java8-installer'
#    question: 'shared/accepted-oracle-license-v1-1'
#    value: 'true'
#    vtype: 'select'

- name: install oracle java
  block:

    - name: stat oracle java directory
      stat:
        path: "/opt/jdk/{{ oracle_java_dir }}"
      register: oracle_java_dir_stat
      tags:
        - oracle_java_tar

    - name: Download java jdk rpm
      get_url:
        url: "{{ oracle_java_tar }}"
        dest: /tmp/jdk.x86_64.tgz
        headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
        validate_certs: no
        force: yes
      when: not oracle_java_dir_stat.stat.exists
      register: jdk_downloaded
      tags:
        - download_jdk_tar
        - oracle_java_tar

    - name: ensure target path for jdk exists
      file:
        path: "/opt/jdk"
        state: directory
      tags:
        - oracle_java_tar

    - name: unarchive java tar
      unarchive:
        src: /tmp/jdk.x86_64.tgz
        dest: "/opt/jdk"
      when: >
            not oracle_java_dir_stat.stat.exists or
            (jdk_downloaded and jdk_downloaded.changed)
      tags:
        - oracle_java_tar

    - name: set java environment
      shell: "update-alternatives --install /usr/bin/java java /opt/jdk/{{ oracle_java_dir }}/bin/java 10000"
      register: java_env
      changed_when: "java_env.stdout != ''"

    - name: set javac environment
      shell: "update-alternatives --install /usr/bin/javac javac /opt/jdk/{{ oracle_java_dir }}/bin/javac 10000"
      register: javac_env
      changed_when: "javac_env.stdout != ''"

- name: Install some packages
  apt: state=latest name={{ item }} update_cache=yes
  with_items:
    - maven
    - jq
    - ufw
    - wget
    - lsof
    - curl
    - pv
    - nano
    - sysstat
    - atop
    - htop
    - pastebinit

#- name: Install oracle-java8-set-default
#  apt: state=latest name=oracle-java8-set-default update_cache=yes

- name: set java home environment
  lineinfile:
    path: /etc/environment
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME="/usr/lib/jvm/java-8-oracle"'
