- import_tasks: deps.yml
  tags:
    - iri_deps

- import_tasks: firewalld.yml
  tags:
    - iri_firewalld
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- import_tasks: ufw.yml
  tags:
    - iri_ufw
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_tasks: iri.yml
  tags:
    - iri_config
