- import_tasks: deps_apt.yml
  tags:
    - iri_deps_apt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_tasks: deps_yum.yml
  tags:
    - iri_deps_yum
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- import_tasks: firewalld.yml
  tags:
    - iri_firewalld
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- import_tasks: ufw.yml
  tags:
    - iri_ufw
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_tasks: iri.yml
  tags:
    - iri_config
