- name: ensure private key directory
  file:
    state: directory
    path: /etc/ssl/private
    mode: 0710
    owner: root
    group: root

- name: stat certificate file
  stat:
    path: "{{ ssl_cert_file }}"
  register: cert_file

- name: stat key file
  stat:
    path: "{{ ssl_key_file }}"
  register: key_file

- name: Create self-signed SSL key and certificate
  shell: 'openssl req -x509 -nodes -days {{ ssl_default_days }} -newkey rsa:{{ ssl_rsa_bits }} -keyout {{ ssl_key_file }} -out {{ ssl_cert_file }} -subj "{{ ssl_subject }}"'
  when: >
        not cert_file.stat.exists or
        not key_file.stat.exists

- name: Set permissions on key file
  file:
    path: "{{ ssl_key_file }}"
    owner: root
    group: root
    mode: 0400 
