- name: Install epel-release
  yum: state=latest name=epel-release

- name: Install some packages
  yum: state=latest name={{ item }}
  with_items:
    - nodejs
    - firewalld
    - curl
    - lsof

- name: Install iota-pm package
  npm:
    name: iota-pm
    version: "{{ iotapm_version }}"
    global: yes
