- name: Install epel-release
  yum: state=latest name=epel-release
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install some packages
  yum: state=latest name={{ item }}
  with_items:
    - nodejs
    - firewalld
    - curl
    - lsof
    - python-passlib
    - httpd-tools
    - nginx
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install nginx packages
  yum: state=latest name={{ item }}
  with_items:
    - python-passlib
    - httpd-tools
    - nginx
  when: >
        install_nginx is defined and install_nginx and
        (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: Install some packages
  apt: state=latest name={{ item }} update_cache=yes
  with_items:
    - lsof
    - curl
    - nodejs
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install nginx packages
  apt: state=latest name={{ item }} update_cache=yes
  with_items:
    - nginx
    - python-passlib
    - apache2-utils
  when: >
        install_nginx is defined and install_nginx and
        (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Install iota-pm package
  npm:
    name: iota-pm
    version: "{{ iotapm_version }}"
    global: yes
