- name: ensure firewalld started and enabled
  systemd:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: allow iota-pm tcp port in firewall
  firewalld:
    port: "{{ iotapm_port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  when: >
        iotapm_allow_firewall is defined and
        iotapm_allow_firewall and
        (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: allow iota-pm tcp port in firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ iotapm_port }}"
  when: >
        iotapm_allow_firewall is defined and
        iotapm_allow_firewall and
        (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: allow iotapm nginx port in firewall
  firewalld:
    port: "{{ iotapm_nginx_port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: allow iotapm nginx port via selinux seport
  seport:
    ports: "{{ iotapm_nginx_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: allow nginx to revese proxy
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: allow iotapm nginx port in firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ iotapm_nginx_port }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
