- name: uninstall iota-pm package
  npm:
    name: iota-pm
    version: "{{ iotapm_version }}"
    global: yes
    state: absent

- name: remove iota-pm tcp ports in firewall
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: absent
    immediate: yes
  with_items:
    - "{{ iotapm_port }}/tcp"
    - "{{ iotapm_nginx_port }}/tcp"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: remove iota-pm tcp port in firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    delete: yes
    port: "{{ item }}"
  with_items:
    - "{{ iotapm_nginx_port }}"
    - "{{ iotapm_port }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: set variables centos/redhat
  set_fact:
    systemd_dir: /usr/lib/systemd/system
    config_dir: /etc/sysconfig
    nodejs_bin: /usr/bin/node
    iotapm_bin: /bin/iota-pm
    nginx_group: nginx
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: set variables debian/ubuntu
  set_fact:
    systemd_dir: /etc/systemd/system
    config_dir: /etc/default
    nodejs_bin: /usr/bin/nodejs
    iotapm_bin: /usr/bin/iota-pm
    nginx_group: www-data
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: stop iotapm
  systemd:
    name: iota-pm
    state: stopped
    enabled: false
  ignore_errors: yes

- name: remove systemd service file
  file:
    path: "{{ systemd_dir }}/iota-pm.service"
    state: absent
  notify:
    - reload systemd

- name: remove the user for iotapm
  user:
    name: "{{ iotapm_username }}"
    state: absent
    remove: yes

- name: remove iotapm related files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/var/spool/iotapm"
    - "{{ config_dir }}/iota-pm"
    - "/usr/local/bin/validate_nginx_config.sh"
    - "/etc/nginx/conf.d/ssl.cfg"
    - "/etc/nginx/conf.d/iotapm.conf"

- name: remove iotapm nginx password
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: '{{ iotapm_nginx_user }}'
    state: absent
